//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace ServiceLayer.Services
{
    using DataLayer.Model;
    using DataLayer.Data;
    using RepositoryLayer;
    using RepositoryLayer.Interfaces;
    using System.Threading.Tasks;
    
    using DataLayer.Requests;
    using DataLayer.Results;
    using System.Linq;
    
    public partial class UserProfileService : IService<UserProfileData, UserProfile>
    {
    	protected IQuery<UserProfileData, UserProfile> _query;
    	protected ICreateCommand<UserProfileData> _createCommand;
    	protected IUpdateCommand<UserProfileData> _updateCommand;
    	protected IDeleteCommand<UserProfileData> _deleteCommand;
    
    	public UserProfileService(IQuery<UserProfileData, UserProfile> query,
    		 ICreateCommand<UserProfileData> createCommand,
    		 IUpdateCommand<UserProfileData> updateCommand,
    		 IDeleteCommand<UserProfileData> deleteCommand)
    	{
    		_query = query;
    		_createCommand = createCommand;
    		_updateCommand = updateCommand;
    		_deleteCommand = deleteCommand;
    	}
    
    	public virtual async Task<CommandResult<UserProfileData>> Create(UserProfileData data)
    	{
    		try
            {
                return await _createCommand.Create(data);
            } 
    		catch (Exception ex)
            {
    			//TODO Trace ex
    			return new CommandResult<UserProfileData>(data, ex);
    		}
    	}
    
    	public virtual async Task<CommandResult<UserProfileData>> Update(UserProfileData data)
    	{
    		try
            {
                return await _updateCommand.Update(data);
            } 
    		catch (Exception ex)
            {
    			//TODO Trace ex
    			return new CommandResult<UserProfileData>(data, ex);
    		}
    	}
    
    	public virtual async Task<CommandResult<UserProfileData>> Delete(UserProfileData data)
    	{
    		try
            {
                return await _deleteCommand.Delete(data);
            } 
    		catch (Exception ex)
            {
    			//TODO Trace ex
    			return new CommandResult<UserProfileData>(data, ex);
    		}
    	}
    
    	public async Task<FindResult<UserProfileData>> Find(params object[] keyValues)
    	{
    		try
            {
                return await _query.Find(keyValues);
            } 
    		catch (Exception ex)
            {
     			//TODO Trace ex
    			return new FindResult<UserProfileData>(ex);
    		}
    	}
    
    	public async Task<WhereResult<UserProfileData>> Where(PaginatedRequest req, Func<UserProfile, bool> predicate)
    	{
    		try
            {
                return await _query.Where(req, predicate);
            }
    		catch (Exception ex)
            {
     			//TODO Trace ex
    			return new WhereResult<UserProfileData>(ex);
    		}
    	}
    }
}
