//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace ServiceLayer.Services
{
    using DataLayer.Model;
    using DataLayer.Data;
    using RepositoryLayer;
    using RepositoryLayer.Interfaces;
    using System.Threading.Tasks;
    
    using DataLayer.Requests;
    using DataLayer.Results;
    using System.Linq;
    
    public partial class UserService : IService<UserData, User>
    {
    	protected IQuery<UserData, User> _query;
    	protected ICreateCommand<UserData> _createCommand;
    	protected IUpdateCommand<UserData> _updateCommand;
    	protected IDeleteCommand<UserData> _deleteCommand;
    
    	public UserService(IQuery<UserData, User> query,
    		 ICreateCommand<UserData> createCommand,
    		 IUpdateCommand<UserData> updateCommand,
    		 IDeleteCommand<UserData> deleteCommand)
    	{
    		_query = query;
    		_createCommand = createCommand;
    		_updateCommand = updateCommand;
    		_deleteCommand = deleteCommand;
    	}
    
    	public virtual async Task<CommandResult<UserData>> Create(UserData data)
    	{
    		try
            {
                return await _createCommand.Create(data);
            } 
    		catch (Exception ex)
            {
    			//TODO Trace ex
    			return new CommandResult<UserData>(data, ex);
    		}
    	}
    
    	public virtual async Task<CommandResult<UserData>> Update(UserData data)
    	{
    		try
            {
                return await _updateCommand.Update(data);
            } 
    		catch (Exception ex)
            {
    			//TODO Trace ex
    			return new CommandResult<UserData>(data, ex);
    		}
    	}
    
    	public virtual async Task<CommandResult<UserData>> Delete(UserData data)
    	{
    		try
            {
                return await _deleteCommand.Delete(data);
            } 
    		catch (Exception ex)
            {
    			//TODO Trace ex
    			return new CommandResult<UserData>(data, ex);
    		}
    	}
    
    	public async Task<FindResult<UserData>> Find(params object[] keyValues)
    	{
    		try
            {
                return await _query.Find(keyValues);
            } 
    		catch (Exception ex)
            {
     			//TODO Trace ex
    			return new FindResult<UserData>(ex);
    		}
    	}
    
    	public async Task<WhereResult<UserData>> Where(PaginatedRequest req, Func<User, bool> predicate)
    	{
    		try
            {
                return await _query.Where(req, predicate);
            }
    		catch (Exception ex)
            {
     			//TODO Trace ex
    			return new WhereResult<UserData>(ex);
    		}
    	}
    }
}
