//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using DataLayer.Model;

public partial class DataModelContainer : DbContext
{
    public DataModelContainer()
        : base("name=DataModelContainer")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<User> UserSet { get; set; }
    public virtual DbSet<UserProfile> UserProfileSet { get; set; }
    public virtual DbSet<Role> RoleSet { get; set; }
}
