//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace DataLayer.Model
{
    
    public partial class UserProfile
    {
        public int Id { get; set; }
        public string IdUser { get; set; }
        public string Name { get; set; }
        public string FirstSurname { get; set; }
        public string LastSurname { get; set; }
    
        public virtual User User { get; set; }
    }
}
