//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
namespace RepositoryLayer.Repositories
{
    using DataLayer.Model;
    using DataLayer.Data;
    using System.Threading.Tasks;
    using System.Data.Entity;
    using DataLayer.Requests;
    using DataLayer.Results;
    using System.Linq;
    using RepositoryLayer.Interfaces;
    
    public partial class UserQuery : IQuery<UserData, User>
    {
    	protected DataModelContainer _context;
    
    	public UserQuery(DataModelContainer context)
    	{
    		_context = context;
    	}
    
    	public virtual async Task<FindResult<UserData>> Find(params object[] keyValues)
    	{
    		var entity = await _context.UserSet.FindAsync(keyValues);
    		return new FindResult<UserData>(new UserData(entity));
    	}
    
    	public virtual async Task<WhereResult<UserData>> Where(PaginatedRequest req, Func<User, bool> predicate)
    	{
    		var count = await _context.UserSet.CountAsync(u => predicate(u));
    		var list = await _context.UserSet.Where(predicate)
                .Skip(req.CurrentPage * req.ItemPerPage)
                .Take(req.ItemPerPage)
    			.Select(i => new UserData(i)).AsQueryable().ToListAsync();
    		return new WhereResult<UserData>( new PaginatedResult<UserData>(req, totalItems: count, items: list));
    	}
    }
}
