//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using ValidationLayer.Interfaces;
using DataLayer.Data;

using System;
using System.Collections.Generic;
namespace ValidationLayer.DefaultValidators
{
    
    internal  class DefaultRoleDataValidator : IValidatorStep<RoleData>
    {
    
    	bool IValidatorStep<RoleData>.IsValid(RoleData data, IList<InvalidProperty> errors)
    	{
    		var nullReason = "The property can't be null";
    		var lengthReason = "The property can't be longer than ";
    		if(data.Id == null) errors.Add(new InvalidProperty(nameof(data.Id), nullReason));
    		if(data.Name == null) errors.Add(new InvalidProperty(nameof(data.Name), nullReason));
    		if(data.Name != null && data.Name.Length > 100) errors.Add(new InvalidProperty(nameof(data.Name), lengthReason + 100));
    		return errors.Count == 0;
    	}
    }
}
