//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using DataLayer.Model;
using System.Linq;

using System;
using System.Collections.Generic;
namespace DataLayer.Data
{
    
    public partial class RoleData
    {
        public int Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserData> Users { get; set; }
    
    	public RoleData() 
    	{
    		this.Users = new HashSet<UserData>(); 
    	}
    
    	public RoleData(Role source, bool deepCopy = true)
    	{
    		this.Id = source.Id;
    		this.Name = source.Name;
    		if(deepCopy)
    		{
    			this.Users = source.Users.Select(i => new UserData(i, deepCopy: false)).ToList();
    		}
    	} 
    	
    	public Role ToEntity()
    	{
    		var entity = new Role();
    		entity.Id = this.Id;
    		entity.Name = this.Name;
    		return entity;
    	}
    }
}
