//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using DataLayer.Model;
using System.Linq;

using System;
using System.Collections.Generic;
namespace DataLayer.Data
{
    
    public partial class UserData
    {
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    
        public virtual UserProfileData UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleData> Roles { get; set; }
    
    	public UserData() 
    	{
    		this.Roles = new HashSet<RoleData>(); 
    	}
    
    	public UserData(User source, bool deepCopy = true)
    	{
    		this.Id = source.Id;
    		this.Email = source.Email;
    		this.Password = source.Password;
    		this.Salt = source.Salt;
    		this.Created = source.Created;
    		this.Updated = source.Updated;
    		if(deepCopy)
    		{
    			if(source.UserProfile != null)
    			{
    				this.UserProfile = new UserProfileData(source.UserProfile, deepCopy: false);
    			}
    			if(source.Roles != null)
    			{
    				this.Roles = source.Roles.Select(i => new RoleData(i, deepCopy: false)).ToList();
    			}
    		}
    	} 
    	
    	public User ToEntity()
    	{
    		var entity = new User();
    		entity.Id = this.Id;
    		entity.Email = this.Email;
    		entity.Password = this.Password;
    		entity.Salt = this.Salt;
    		entity.Created = this.Created;
    		entity.Updated = this.Updated;
    		return entity;
    	}
    }
}
